[serve]
deps=["build"]
exec="cd site && python -m SimpleHTTPServer 8888"

[build]
deps=["site/index.html", "site/bw.html"]

["site/%.html"]
deps=["src/%.js", "src/page.js", "src/custom.js"]
exec="node $< >$@"