import {
  a,
  article,
  body,
  h1,
  h2,
  head,
  html,
  img,
  link,
  meta,
  p,
  script,
  section,
  title,
  v
} from 'ez-html-elements'

import {
  marginNote,
  newThought,
  subTitle
} from './custom.js'

const c = v('c')
const z = v('z')

export default content => '<!doctype html>' +
    html({ lang: 'en' },
      head(
        meta({ charset: 'utf-8' }),
        meta({ name: 'a showcase for Mandelbrot set images generated by the almondbread software' }),
        title('Exploring the Mandelbrot Set'),
        link({ rel: 'stylesheet', href: 'tufte-css-gh-pages/tufte.min.css' }),
        link({ rel: 'stylesheet', href: 'tufte-css-gh-pages/latex.css' }),
        link({ rel: 'stylesheet', href: 'app.css' }),
        meta({ name: 'viewport', content: 'width=device-width, initial-scale=1' }),
        link({ rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' }),
        link({ rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' }),
        link({ rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png' }),
        link({ rel: 'manifest', href: '/site.webmanifest' }),
        script({ src: 'app.js', defer: true }),
        meta({ name: 'twitter:card', content: 'summary_large_image' }),
        meta({ name: 'twitter:creator', content: '@eob' }),
        meta({ property: 'og:url', content: 'https://mandelbrot.dev/' }),
        meta({ property: 'og:title', content: 'Exploring the Mandelbrot Set' }),
        meta({ property: 'og:description', content: 'A showcase of Mandlebrot set images' }),
        meta({ property: 'og:image', content: 'https://mandelbrot.dev/img/770x433_-0.18271806444477842_0.6614075685543184_1.4551915228366852e-11_100000.png' })),
      body(
        article(
          h1('Exploring the Mandelbrot Set'),
          subTitle('Eamonn O\'Brien-Strain'),

          section(
            p(
              newThought('This site'),
              'is a showcase for Mandelbrot set images generated by the',
              a({ href: 'https://github.com/eobrain/almondbread' },
                'almondbread software') + '.',
              marginNote(
                'For more background on my fascination with this set and the development of the software see',
                a({ href: 'https://eamonn.org/programming/2021/01/02/almond-bread.html' },
                  'Finding Mandelbrot images to use as video conference background'))),
            p(`
                  Click on any image to view a full-resolution version, suitable for example
                  as a video conferencing background.`)),
          section(
            h2('What you are looking at'),
            p(newThought('These are images'), 'of the space of complex numbers.'),
            p(
              'The black area is the Mandelbrot set itself, which are the values of the complex number',
              c,
              'such that if you repeatedly iterate',
              z, '←', z + '² +', c, 'starting at', z + '=0 the value of |' + z +
                    '| stays less than 2. The colored areas surrounding the black of the Mandelbrot set are values of',
              c, 'for which', z, 'eventually goes to infinity, with the colors indicating how many iterations until |' + z +
                    '|>2'),
            p(`You will also notice a subtle shading which seems to show relief.
                     This is done by considering that the colored bands to be contours on a map
                     and shading it accordingly to show the slope.`,
            marginNote(
              'For a detailed discussion of the algorithm see',
              a({ href: 'https://eamonn.org/programming/2021/01/29/mandelbrot-3.html' },
                'Hill-Shading the Mandelbrot Set')),
            p('Out of these simple mathematical operations we get these incredibly complex and fascinating images.')),
            content,
            section(
              p({
                xmlns: {
                  cc: 'http://creativecommons.org/ns#',
                  dct: 'http://purl.org/dc/terms/'
                }
              },
              a({ property: 'dct:title', rel: 'cc:attributionURL', href: 'https://mandelbrot.dev' },
                'mandelbrot.dev website'),
              'by',
              a({
                rel: 'cc:attributionURL dct:creator',
                property: 'cc:attributionName',
                href: 'https://twitter.com/eob'
              }, "Eamonn O'Brien-Strain"),
              'is licensed under',
              a({
                href: 'http://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1',
                target: '_blank',
                rel: 'license noopener noreferrer',
                style: 'display:inline-block;'
              }, 'CC BY-NC-ND 4.0'),
              img({
                style: 'height:22px!important;margin-left:3px;vertical-align:text-bottom;',
                src: 'https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1',
                alt: 'CC'
              }),
              img({
                style: 'height:22px!important;margin-left:3px;vertical-align:text-bottom;',
                src: 'https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1',
                alt: 'by'
              }),
              img({
                style: 'height:22px!important;margin-left:3px;vertical-align:text-bottom;',
                src: 'https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1',
                alt: 'NC'
              }),
              img({
                style: 'height:22px!important;margin-left:3px;vertical-align:text-bottom;',
                src: 'https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1',
                alt: 'ND'
              })))))))
